<?php if ($this->pageCount): ?>
    <ul class="pagination pagination-sm">
        <?php if (isset($this->previous)): ?>
            <li><a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->previous; ?>"><<</a></li>
        <?php else: ?>
            <li class="disabled">
                <a href="#" onclick="return false;">
                    <<
                </a>
            </li>
        <?php endif;?>

    </ul>
<?php endif;?>