<script src="http://code.jquery.com/jquery-1.8.3.js">
</script>
<?php
    $title = 'Change role';
    $this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
    $form = $this->form;
    //$form->setAttribute('action', $this->url('album', array('action' => 'add')));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    echo $this->formRow($form->get('role'));
    //echo $this->formRow($form->get('submit'));
    echo $this->form()->closeTag();