<script src="http://code.jquery.com/jquery-1.8.3.js">
</script>
<?php
    $title = 'Change role';
    $this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
    $form = $this->form;
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();

?>

<script>
    function change(){

    }
</script>