<div class=''>
    <div class="well">
        <?php
        $form->setAttribute('action', $this -> url ('admin/category', array('action'=>'edit', 'id' => $id)));
        $form->prepare();

        echo $this->form()->openTag($form);
            echo '<fildset><legend>Редактирование категории</legend>';
            foreach ($form as $element){
                echo "<div class='form-group'>";
                $attributes = $element->getAttributes();

                if ($element->getLabel()){
                    $element->setLabelAttributes(array('class'=>''));
                    if (isset($attributes['required'])){
                        $element->setLabel($element->getLabel()."*");
                    }
                }

                if (isset($attributes['type']) && $attributes['type'] == 'text'){
                    echo $this->formLabel($element);
                    echo "<div>";
                    echo $this->formInput($element);
                    echo "</div>";
                }

                elseif (isset($attributes['type']) && $attributes['type'] == 'textarea'){
                    echo $this->formLabel($element);
                    echo "<div>";
                    echo $this->formInput($element);
                    echo "</div>";
                }
                else {
                    echo '<div>';
                    echo $this->formRow($element);
                    echo '</div>';
                }
                echo "</div>";
            }
            echo '</fildset>';
        echo $this->form()->closeTag();

        ?>
    </div>
</div>