<?php

foreach ($articles as $item) {
    $category = $item->getCategory();
    if ($category) {
        $catName = $category->getCategoryName();
    } else {
        $catName='';
    }

    $url = $this->url('blog', array('action'=>'article', 'id'=>$item->getId()));
    echo "<arcticle class='panel panel-default'>
        <div class='page-header' style='margin-top: 17px'>
            <h4 style='padding-left: 30px; font-size: 25px'><a style='color: black;' href='{$url}'>{$item->getTitle()}</a> </h4>
        </div>
        <div>
            {$item->getShortArticleForBlog()}
        </div>
        <div class='panel-footer' style='height: 45px'>
            <div style='width: 300px; float: left;'>
               Категория: {$catName}
            </div>
            <span style='float: right'>
            <a href='{$url}'>Читать далее...</a>
            </span>
        </div>
        </arcticle>";
}
echo $this->paginationControl($articles,'Sliding','pagination_control', array('route'=>'blog'));
?>